import asyncio
import os
import subprocess
import httpx
from idea_scout.config import DB_PATH, OMNIROUTE_BASE, CODER_MODEL
from idea_scout.db import IdeaDB
from idea_scout.notify import notify_build_complete
from .spec_writer import generate_spec
from .code_builder import generate_code, fix_with_unstuck, parse_code_blocks


PROTOTYPES_DIR = os.path.expanduser("~/prototypes")
UV_BIN = os.path.expanduser("~/.local/bin/uv")
MAX_UNSTUCK_RETRIES = 2

README_PROMPT = """Write a short README.md (under 25 lines) for this mobile app.

App name: {app_name}
What it does: {summary}
Monetization: {monetization}
Audience: {audience}
Tech: React Native (Expo)

Format EXACTLY like this (fill in the blanks, do not add sections):

# AppName

One sentence describing what the app does and who it's for.

## Features

- Feature one
- Feature two
- Feature three

## Monetization

One line: pricing model and price point.

## Run

```bash
npx expo start
```"""


def _update_root_readme():
    """Regenerate the root README.md with all prototype entries."""
    try:
        db = IdeaDB(DB_PATH)
        entries = []
        for dirname in sorted(os.listdir(PROTOTYPES_DIR)):
            if not dirname.startswith("idea-"):
                continue
            project_dir = os.path.join(PROTOTYPES_DIR, dirname)

            # Get app name from spec.md H1, then README H1
            app_name = None
            for fname in ["spec.md", "README.md"]:
                fpath = os.path.join(project_dir, fname)
                if os.path.exists(fpath):
                    with open(fpath) as f:
                        for line in f:
                            if line.strip().startswith("# "):
                                app_name = line.strip()[2:].strip()[:35]
                                break
                    if app_name:
                        break

            # Get idea from DB
            idea = None
            parts = dirname.split("-")
            if len(parts) >= 3:
                if parts[1] == "hn":
                    idea = db.get_post(f"hn-{parts[2]}")
                elif parts[1] == "web":
                    idea = db.get_post(f"web-{parts[2]}")

            analysis = (idea.get("analysis", "") or "") if idea else ""
            summary = analysis.split("\n")[0] if analysis else ""
            score = idea.get("viability_score") if idea else None

            if not app_name:
                app_name = (idea["title"] if idea else dirname)[:35]

            # Trim verbose prefixes
            desc = summary[:120].strip().rstrip(".")
            for prefix in ["A mobile app that ", "A mobile-first ", "An AI-powered ", "A comprehensive "]:
                if desc.startswith(prefix):
                    desc = desc[len(prefix):]
                    desc = desc[0].upper() + desc[1:] if desc else desc
                    break

            entries.append((dirname, app_name, desc, score))

        lines = [
            "# Prototypes", "",
            f"{len(entries)} mobile app prototypes, auto-generated by the idea pipeline.", "",
            "| App | Description | Score |",
            "|-----|-------------|-------|",
        ]
        for dirname, name, desc, score in sorted(entries, key=lambda x: -(x[3] or 0)):
            score_str = f"{score}/10" if score else "--"
            lines.append(f"| [{name}]({dirname}/) | {desc or '--'} | {score_str} |")

        readme_path = os.path.join(PROTOTYPES_DIR, "README.md")
        with open(readme_path, "w") as f:
            f.write("\n".join(lines) + "\n")
    except Exception as e:
        print(f"  Root README update failed: {type(e).__name__}")


def _parse_analysis(analysis: str) -> tuple[str, dict]:
    """Parse analysis into (summary, parts dict)."""
    lines = analysis.split("\n")
    summary = lines[0] if lines else ""
    parts = {}
    for line in lines[1:]:
        if ":" in line:
            key = line.split(":")[0].strip()
            val = ":".join(line.split(":")[1:]).strip()
            if val:
                parts[key] = val
    return summary, parts


def _get_spec_app_name(spec: str) -> str:
    """Extract app name from spec H1."""
    for line in spec.split("\n"):
        if line.strip().startswith("# "):
            return line.strip()[2:].strip()
    return ""


async def _generate_readme(
    client: httpx.AsyncClient, idea: dict, spec: str,
    file_names: list[str], status: str,
) -> str:
    """Generate a README from the idea + spec."""
    analysis = idea.get("analysis", "") or ""
    summary, parts = _parse_analysis(analysis)
    app_name = _get_spec_app_name(spec) or idea.get("title", "App")
    source_url = idea.get("source_url") or idea.get("permalink", "")

    try:
        resp = await client.post(
            f"{OMNIROUTE_BASE}/chat/completions",
            json={
                "model": CODER_MODEL,
                "messages": [{"role": "user", "content": README_PROMPT.format(
                    app_name=app_name,
                    summary=summary[:200],
                    monetization=parts.get("Monetization", "Freemium")[:100],
                    audience=parts.get("Audience", "")[:100],
                )}],
                "temperature": 0.3,
                "max_tokens": 400,
            },
            timeout=60,
        )
        resp.raise_for_status()
        readme = resp.json()["choices"][0]["message"]["content"]
    except Exception as e:
        print(f"  README generation failed: {type(e).__name__}, using fallback")
        readme = (
            f"# {app_name}\n\n"
            f"{summary[:200]}\n\n"
            f"## Run\n\n```bash\nnpx expo start\n```\n"
        )

    # Append source link
    if source_url:
        readme = readme.rstrip() + f"\n\n## Origin\n\nInspired by: {source_url}\n"

    return readme


def write_files(project_dir: str, files: dict[str, str]):
    for path, content in files.items():
        full_path = os.path.join(project_dir, path)
        os.makedirs(os.path.dirname(full_path), exist_ok=True)
        with open(full_path, "w") as f:
            f.write(content)


def try_install_and_test(project_dir: str) -> tuple[bool, str]:
    """Try to install deps and run tests. Returns (success, error_output)."""
    # Check for requirements.txt or package.json
    req_txt = os.path.join(project_dir, "requirements.txt")
    pkg_json = os.path.join(project_dir, "package.json")

    if os.path.exists(req_txt):
        r = subprocess.run(
            [UV_BIN, "pip", "install", "-r", "requirements.txt", "--python", "python3"],
            cwd=project_dir, capture_output=True, text=True, timeout=120,
        )
        if r.returncode != 0:
            return False, f"pip install failed:\n{r.stderr}"
    elif os.path.exists(pkg_json):
        r = subprocess.run(
            ["npm", "install"], cwd=project_dir,
            capture_output=True, text=True, timeout=120,
        )
        if r.returncode != 0:
            return False, f"npm install failed:\n{r.stderr}"

    # Try running tests if they exist
    test_dir = os.path.join(project_dir, "tests")
    test_file = os.path.join(project_dir, "test_app.py")
    if os.path.isdir(test_dir) or os.path.exists(test_file):
        r = subprocess.run(
            ["python3", "-m", "pytest", "-x", "--tb=short"],
            cwd=project_dir, capture_output=True, text=True, timeout=60,
        )
        if r.returncode != 0:
            return False, f"Tests failed:\n{r.stdout}\n{r.stderr}"

    # Syntax check all .py files
    for root, _, fnames in os.walk(project_dir):
        for fname in fnames:
            if fname.endswith(".py"):
                fpath = os.path.join(root, fname)
                r = subprocess.run(
                    ["python3", "-c", f"import ast; ast.parse(open('{fpath}').read())"],
                    capture_output=True, text=True, timeout=10,
                )
                if r.returncode != 0:
                    return False, f"Syntax error in {fname}:\n{r.stderr}"

    return True, ""


async def build_next_prototype():
    db = IdeaDB(DB_PATH)
    # Use get_buildable_ideas (requires viability >= 7 AND competition >= 4)
    ideas = db.get_buildable_ideas(limit=1)

    if not ideas:
        print("No buildable ideas")
        return

    idea = ideas[0]
    print(f"Building prototype for: {idea['title']}")

    # Step 1: Generate spec (planner model) — mark started only after spec succeeds
    print("  [planner] Generating spec...")
    spec = await generate_spec(idea)
    db.mark_prototype_started(idea["id"])

    # Step 2: Generate code (coder model)
    async with httpx.AsyncClient(timeout=300) as client:
        print("  [coder] Generating code...")
        code_response = await generate_code(client, spec)
        files = parse_code_blocks(code_response)

        # Create project directory
        safe_name = "".join(
            c if c.isalnum() or c in "-_" else "-"
            for c in idea["title"].lower()
        )[:40].strip("-")
        project_dir = os.path.join(PROTOTYPES_DIR, f"idea-{idea['id']}-{safe_name}")
        os.makedirs(project_dir, exist_ok=True)

        # Write spec
        with open(os.path.join(project_dir, "spec.md"), "w") as f:
            f.write(spec)

        # Write generated code
        write_files(project_dir, files)
        print(f"  Wrote {len(files)} files")

        # Step 3: Validate and escalate if needed
        success, error = try_install_and_test(project_dir)
        retries = 0
        while not success and retries < MAX_UNSTUCK_RETRIES:
            retries += 1
            print(f"  [unstuck] Attempt {retries}/{MAX_UNSTUCK_RETRIES}: {error[:100]}")
            fixed_response = await fix_with_unstuck(client, spec, code_response, error)
            fixed_files = parse_code_blocks(fixed_response)
            if fixed_files:
                write_files(project_dir, fixed_files)
                code_response = fixed_response
                print(f"  Rewrote {len(fixed_files)} files")
            success, error = try_install_and_test(project_dir)

        status = "working" if success else f"needs-fix (after {retries} unstuck attempts)"
        print(f"  Status: {status}")

        # Step 4: Generate README
        readme = await _generate_readme(client, idea, spec, list(files.keys()), status)
        with open(os.path.join(project_dir, "README.md"), "w") as f:
            f.write(readme)

    # Update root README
    _update_root_readme()

    # Commit and push
    subprocess.run(["git", "add", "."], cwd=PROTOTYPES_DIR)
    subprocess.run(
        ["git", "commit", "-m", f"feat: prototype for {safe_name} [{status}]"],
        cwd=PROTOTYPES_DIR,
    )
    subprocess.run(["git", "push"], cwd=PROTOTYPES_DIR)

    # Notify
    await notify_build_complete(idea, status, len(files))

    print(f"Done: {project_dir}")


def main():
    asyncio.run(build_next_prototype())


if __name__ == "__main__":
    main()
