export const AppConstants = {
  MAX_FREE_GLANCEABLE_TASKS: 3,
  NOTIFICATION_CATEGORY_ID: 'AURA_NOTIFICATIONS',
  NOTIFICATION_ACTION_COMPLETE: 'COMPLETE',
  NOTIFICATION_ACTION_SNOOZE: 'SNOOZE',
  WIDGET_DATA_KEY: 'AURA_WIDGET_DATA',
  PREMIUM_PRODUCT_ID: 'aura_premium_subscription',
};
