export const themes = [
  {
    id: 'minimal',
    name: 'Minimal',
    background: '#FFFFFF',
    text: '#000000',
    widgetBackground: 'rgba(0, 0, 0, 0.05)',
    drawerBackground: '#F5F5F5',
    dark: false,
  },
  {
    id: 'warm',
    name: 'Warm',
    background: '#FFF8E1',
    text: '#5D4037',
    widgetBackground: 'rgba(93, 64, 55, 0.1)',
    drawerBackground: '#FFECB3',
    dark: false,
  },
  {
    id: 'cool',
    name: 'Cool',
    background: '#E3F2FD',
    text: '#1976D2',
    widgetBackground: 'rgba(25, 118, 210, 0.1)',
    drawerBackground: '#BBDEFB',
    dark: false,
  },
  {
    id: 'nature',
    name: 'Nature',
    background: '#E8F5E9',
    text: '#2E7D32',
    widgetBackground: 'rgba(46, 125, 50, 0.1)',
    drawerBackground: '#C8E6C9',
    dark: false,
  },
  {
    id: 'night',
    name: 'Night',
    background: '#121212',
    text: '#FFFFFF',
    widgetBackground: 'rgba(255, 255, 255, 0.1)',
    drawerBackground: '#1E1E1E',
    dark: true,
  },
];
