// Mock database of weapons and armor from various games
export const WEAPONS_DB = [
  // Destiny 2 Weapons
  {
    id: 'w1',
    name: 'Fatebringer',
    game: 'Destiny 2',
    attack: 95,
    defense: 0,
    special: 'Explosive Payload',
    type: 'Hand Cannon',
  },
  {
    id: 'w2',
    name: 'Gjallarhorn',
    game: 'Destiny 2',
    attack: 120,
    defense: 0,
    special: 'Wolfpack Rounds',
    type: 'Rocket Launcher',
  },
  {
    id: 'w3',
    name: 'Hawkmoon',
    game: 'Destiny 2',
    attack: 88,
    defense: 0,
    special: 'Paracausal Shot',
    type: 'Hand Cannon',
  },
  {
    id: 'w4',
    name: 'Witherhoard',
    game: 'Destiny 2',
    attack: 85,
    defense: 0,
    special: 'Primeval\'s Torment',
    type: 'Grenade Launcher',
  },
  // Warframe Weapons
  {
    id: 'w5',
    name: 'Kuva Bramma',
    game: 'Warframe',
    attack: 110,
    defense: 0,
    special: 'Cluster Bombs',
    type: 'Bow',
  },
  {
    id: 'w6',
    name: 'Kuva Nukor',
    game: 'Warframe',
    attack: 92,
    defense: 0,
    special: 'Chain Beam',
    type: 'Pistol',
  },
  {
    id: 'w7',
    name: 'Ignis Wraith',
    game: 'Warframe',
    attack: 78,
    defense: 0,
    special: 'Flame Thrower',
    type: 'Rifle',
  },
  // Diablo IV Weapons
  {
    id: 'w8',
    name: 'Grandfather',
    game: 'Diablo IV',
    attack: 105,
    defense: 0,
    special: 'Increased Critical Damage',
    type: 'Two-Handed Sword',
  },
  {
    id: 'w9',
    name: 'Doombringer',
    game: 'Diablo IV',
    attack: 98,
    defense: 0,
    special: 'Lucky Hit',
    type: 'One-Handed Sword',
  },
  // Path of Exile Weapons
  {
    id: 'w10',
    name: 'Starforge',
    game: 'Path of Exile',
    attack: 115,
    defense: 0,
    special: 'Shock Enemies',
    type: 'Two-Handed Sword',
  },
];

export const ARMOR_DB = [
  // Destiny 2 Armor
  {
    id: 'a1',
    name: 'Helm of Saint-14',
    game: 'Destiny 2',
    attack: 0,
    defense: 85,
    special: 'Blinding Bubble',
    type: 'Helmet',
  },
  {
    id: 'a2',
    name: 'Orpheus Rig',
    game: 'Destiny 2',
    attack: 0,
    defense: 78,
    special: 'Tether Energy',
    type: 'Legs',
  },
  {
    id: 'a3',
    name: 'Phoenix Protocol',
    game: 'Destiny 2',
    attack: 0,
    defense: 82,
    special: 'Super Energy',
    type: 'Chest',
  },
  // Warframe Armor
  {
    id: 'a4',
    name: 'Adaptation',
    game: 'Warframe',
    attack: 0,
    defense: 95,
    special: 'Damage Resistance',
    type: 'Mod',
  },
  {
    id: 'a5',
    name: 'Rolling Guard',
    game: 'Warframe',
    attack: 0,
    defense: 88,
    special: 'Invulnerability',
    type: 'Mod',
  },
  // Diablo IV Armor
  {
    id: 'a6',
    name: 'Shako',
    game: 'Diablo IV',
    attack: 0,
    defense: 110,
    special: 'All Skills +4',
    type: 'Helmet',
  },
  {
    id: 'a7',
    name: 'Temerity',
    game: 'Diablo IV',
    attack: 0,
    defense: 92,
    special: 'Barrier Generation',
    type: 'Pants',
  },
  {
    id: 'a8',
    name: 'Tibault\'s Will',
    game: 'Diablo IV',
    attack: 0,
    defense: 86,
    special: 'Unstoppable',
    type: 'Pants',
  },
  // Path of Exile Armor
  {
    id: 'a9',
    name: 'Headhunter',
    game: 'Path of Exile',
    attack: 0,
    defense: 105,
    special: 'Steal Mods',
    type: 'Belt',
  },
  {
    id: 'a10',
    name: 'Kaom\'s Heart',
    game: 'Path of Exile',
    attack: 0,
    defense: 120,
    special: '+500 Life',
    type: 'Chest',
  },
  {
    id: 'a11',
    name: 'Shavronne\'s Wrappings',
    game: 'Path of Exile',
    attack: 0,
    defense: 98,
    special: 'Chaos Damage to ES',
    type: 'Chest',
  },
];
