export const themes = [
  {
    id: 'light',
    name: 'Light',
    isPremium: false,
    background: '#FFFFFF',
    cardBackground: '#F5F5F5',
    iconBackground: '#E0E0E0',
    text: '#000000',
  },
  {
    id: 'dark',
    name: 'Dark',
    isPremium: false,
    background: '#121212',
    cardBackground: '#1E1E1E',
    iconBackground: '#2D2D2D',
    text: '#FFFFFF',
  },
  {
    id: 'minimal',
    name: 'Minimal',
    isPremium: false,
    background: '#F8F8F8',
    cardBackground: '#FFFFFF',
    iconBackground: '#F0F0F0',
    text: '#333333',
  },
  {
    id: 'neon',
    name: 'Neon',
    isPremium: true,
    background: '#000000',
    cardBackground: '#1A1A1A',
    iconBackground: '#2D2D2D',
    text: '#00FF00',
  },
  {
    id: 'nature',
    name: 'Nature',
    isPremium: true,
    background: '#E8F5E9',
    cardBackground: '#C8E6C9',
    iconBackground: '#A5D6A7',
    text: '#1B5E20',
  },
  {
    id: 'gradient',
    name: 'Gradient',
    isPremium: true,
    background: 'linear-gradient(to right, #FF9966, #FF5E62)',
    cardBackground: '#FFFFFF',
    iconBackground: '#F5F5F5',
    text: '#333333',
  },
  {
    id: 'retro',
    name: 'Retro',
    isPremium: true,
    background: '#FFD700',
    cardBackground: '#FF6347',
    iconBackground: '#4682B4',
    text: '#FFFFFF',
  },
  {
    id: 'ocean',
    name: 'Ocean',
    isPremium: true,
    background: '#E0F7FA',
    cardBackground: '#B2EBF2',
    iconBackground: '#80DEEA',
    text: '#006064',
  },
];
