export const PROMPT_TEMPLATES = {
  'drill-sergeant': {
    general: [
      'Keep pushing!',
      'No slacking!',
      'You can do better than this!',
      'Move it, move it!',
      'Is that all you got?',
      'Drop and give me 20... more minutes!',
      'Pain is weakness leaving the body!',
      'No excuses, soldier!',
      'You signed up for this!',
      'Finish strong!',
    ],
    encouragement: [
      'Outstanding work!',
      'That\'s what I\'m talking about!',
      'You\'re crushing it!',
      'Keep that momentum!',
      'Solid effort, soldier!',
    ],
    refocus: [
      'Get back in the game!',
      'Focus up!',
      'Eyes on the prize!',
      'No time for breaks!',
      'Back to work!',
    ],
  },
  'zen-master': {
    general: [
      'Stay present',
      'Breathe through it',
      'Find your center',
      'One moment at a time',
      'Peace comes from within',
      'Let go of resistance',
      'Flow with the task',
      'Embrace the process',
      'Be here now',
      'Trust the journey',
    ],
    encouragement: [
      'Beautiful progress',
      'You are exactly where you need to be',
      'Your effort is enough',
      'Well done, my friend',
      'Feel the growth within',
    ],
    refocus: [
      'Return to your breath',
      'Come back to center',
      'Gently redirect your focus',
      'The present moment awaits',
      'Find your way back',
    ],
  },
  'best-friend': {
    general: [
      'You got this, buddy!',
      'I believe in you!',
      'You\'re doing amazing!',
      'So proud of you right now!',
      'Keep going, friend!',
      'You\'re stronger than you think!',
      'I\'m here with you!',
      'You\'re making it happen!',
      'Look at you go!',
      'This is your moment!',
    ],
    encouragement: [
      'Yes! That\'s my friend!',
      'Knew you could do it!',
      'You\'re absolutely killing it!',
      'So happy for you!',
      'That\'s the spirit!',
    ],
    refocus: [
      'Hey, let\'s get back to it',
      'Come on, we can do this',
      'Let\'s finish what we started',
      'You\'ve got this, refocus',
      'Back at it, friend',
    ],
  },
  'comedian': {
    general: [
      'Don\'t worry, it\'s not brain surgery... or is it?',
      'You\'re doing great! Unlike my last relationship',
      'Keep going! The couch will still be there later',
      'This is easier than explaining crypto to your parents',
      'You\'re on fire! Metaphorically, I hope',
      'Look at you, being all productive and stuff',
      'Who needs Netflix when you\'ve got this?',
      'You\'re crushing it like I crush snacks at midnight',
      'This task doesn\'t stand a chance!',
      'You make this look easy... ish',
    ],
    encouragement: [
      'Now that\'s what I call a pro move!',
      'Chef\'s kiss! You nailed it!',
      'Give yourself a high five!',
      'You deserve a trophy for that!',
      'Somebody call the fire department, you\'re too hot!',
    ],
    refocus: [
      'Okay, break time\'s over, back to the grind',
      'Let\'s get back before we forget what we\'re doing',
      'Time to adult again',
      'Alright, let\'s do this thing',
      'Back to business, funny business that is',
    ],
  },
  'stoic': {
    general: [
      'Embrace the challenge',
      'Difficulty reveals character',
      'The obstacle is the way',
      'Control what you can control',
      'This too shall pass',
      'Endure and persist',
      'Virtue through action',
      'Focus on the process',
      'Accept what is',
      'Strength through adversity',
    ],
    encouragement: [
      'You demonstrate wisdom',
      'Your discipline is admirable',
      'Well reasoned, well executed',
      'You honor yourself with this effort',
      'Excellence achieved through persistence',
    ],
    refocus: [
      'Return to what matters',
      'Redirect your attention',
      'The task awaits your focus',
      'Resume your discipline',
      'Back to purposeful action',
    ],
  },
};

export type CoachId = keyof typeof PROMPT_TEMPLATES;
export type PromptCategory = 'general' | 'encouragement' | 'refocus';
